paths:
  /api/business-details:
    post:
      summary: Retrieve Google Places business details.
      description: Fetches detailed information for a business from Google Places API using its name, address, and postal code.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessInput'
      responses:
        '200':
          description: Successfully retrieved business details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessDetailsResponse'
        '400':
          description: Bad request - Missing parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Business not found for the provided information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error or API key missing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    BusinessInput:
      type: object
      required: ['name', 'address', 'postalCode']
      properties:
        name:
          type: string
          description: 'The name of the business.'
          example: 'Musée du Louvre'
        address:
          type: string
          description: 'The street address of the business.'
          example: 'Rue de Rivoli'
        postalCode:
          type: string
          description: 'The postal code of the business.'
          example: '75001'
    BusinessDetailsResponse:
      type: object
      properties:
        name: { type: 'string' }
        address: { type: 'string' }
        phone: { type: 'string' }
        website: { type: 'string' }
        openingHours: { type: 'array', items: { type: 'string' } }
        rating: { type: 'number', format: 'float' }
        reviewCount: { type: 'integer' }
        googleMapsUrl: { type: 'string', format: 'url' }
        placeId: { type: 'string' }
        latitude: { type: 'number', format: 'float' }
        longitude: { type: 'number', format: 'float' }
      example:
        "name": "Musée du Louvre"
        "address": "Rue de Rivoli, 75001 Paris, France"
        "phone": "+33 1 40 20 53 17"
        "website": "http://www.louvre.fr/"
        "openingHours": [
          "lundi: 09:00-18:00",
          "mardi: Fermé",
          "mercredi: 09:00-18:00",
          "jeudi: 09:00-18:00",
          "vendredi: 09:00-21:45",
          "samedi: 09:00-18:00",
          "dimanche: 09:00-18:00"
        ]
        "rating": 4.7
        "reviewCount": 268953
        "googleMapsUrl": "https://maps.google.com/?cid=17565349581333481267"
        "placeId": "ChIJb1G_y31y5kcRWwD9d_Hl75s"
        "latitude": 48.860611
        "longitude": 2.337644
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: 'A message describing the error.'
      example:
        error: 'Missing required parameters: name, address, or postalCode.'